config/routes.rb
Rails.application.routes.draw do
  resources :videos

end

app/models/video.rb
class Video < ActiveRecord::Base

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/video_controller.rb
class VideosController < ApplicationController

app/controllers/videos_controller.rb
class VideosController < ApplicationController
	def create
		@video = Video.new(video_params)
		@video.save
			redirect_to @video

	end

	def new
		@video = Video.new
		puts "NEW"
		puts @video.inspect
	end

	def edit
		@video = Video.find(params[:id])
		
	end

	def update

	end

	def index
		@allvideos = Video.all
		
	end

	def show
		@video = Video.find(params[:id])

	end

	def destroy
	@video = Video.find(params[:id])
  	@video.destroy
 
  	redirect_to videos_path

	end

	private
    # Use callbacks to share common setup or constraints between actions.

    # Never trust parameters from the scary internet, only allow the white list through.
	    def video_params
	      params.require(:video).permit(:title, :link)
	    end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>VideoPlaylist</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
<%= link_to 'HOME', controller: 'videos' %>
<%= link_to 'New Video', new_video_path %>

</head>
<body>

<%= yield %>

</body>
</html>

app/views/videos/_form.html.erb
<p> Please enter a video title</p>

<p> Please enter a video link</p>

<p>
<%= form_for @video do |f| %>

<div>
	<%= f.label :title %>
	<%= f.text_field :title %>
</div>

<div>

	<%= f.label :link %>
	<%= f.text_field :link %>
</div>

<div>
	<%= f.submit %>
<% end %>
</p>













</p>

app/views/videos/edit.html.erb
<p> this is the edit page </p>

<%= form_for :video, url: video_path(@video), method: :patch do |f| %>

	<p>
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </p>
 
  <p>
    <%= f.label :link %><br>
    <%= f.text_area :link %>
  </p>
 
  <p>
    <%= f.submit %>
  </p>
<% end %>
 
<%= link_to 'Back', video_path %>

app/views/videos/index.html.erb
<h1>Hello, Rails!</h1>



<% @allvideos.each do |video| %>
	<hr><%= link_to video.title, video %></hr>
	<%= video.link %>
	<% end %>
	<hr></hr>

app/views/videos/new.html.erb
<p> this is the new page </p>
<%= render 'form.html.erb' %>

app/views/videos/show.html.erb
<h1> Your current Video</h1>	

<h3><%= @video.title %></h3>
<h3><%= @video.link %><h3>

	<%= link_to 'Edit', edit_video_path %>
	<%= link_to 'Destroy', video_path,
                    method: :delete, data: { confirm: 'Are you sure?' } %>
                